### ISSUE TITLE
This is super cool. Would love to see a couple options.

### ISSUE THREAD

**Issue by joshuaiz** [cedaro/wavethumb#1]
Building a headless WP app with React for my record label site and none of the React waveform solutions were working. 

I ended up deciding to generate images of the waveforms and found this. It works really well and better than any of the online waveform png generators. Since I'm using WP Offload S3, the images are automagically uploaded to Amazon S3 so I can serve them from there which is faster than the REST API.

With a couple options, this would be even better:

- select the waveform color/background color (or transparent)
- choose the naming convention

Still, this is excellent so thanks!

**Comment by bradyvercher** [comment]
This was primarily an experiment to satisfy my own curiosity, so I'm glad to hear you find it useful!

I went ahead and pushed a couple of changes with filters so you can apply a custom color and modify the filename format. Hope that helps!

**Comment by joshuaiz** [comment]
Awesome thanks! It took me about 4 hours to generate all the waveforms for all of my tracks so I think I'm stuck with black for this project but the ability to change the colors will be great in the future.

One last feature request while I'm here: it would be great to have a toggle to auto-generate the waveforms on upload if the file is an mp3 or maybe further if it was a 128kbps MP3. That would save someone else having to go to each file and press the 'Generate Waveform' button. That would have saved me loads of time.

Again, thanks for this and the updates.

**Comment by bradyvercher** [comment]
One reason I went with black is that after you've generated the original image, it's possible to extend WordPress' image editor to extract the peak data and modify the image on the server. It shouldn't be too difficult to dynamically generate waveforms with different colors or styles.

I can definitely see how auto-generating waveforms on upload would save some time and I'm pretty sure I looked into it, but since there are so many different ways to upload media and the browser is required for processing the audio, there didn't seem to be a good catch-all. It also wouldn't have helped for audio that had been uploaded previously, so I stuck with the manual process.

**Comment by joshuaiz** [comment]
All good - if I need to I can batch colorize the images in Photoshop so no worries there. I'm using CSS opacity anyway so here's how they are looking:

<img width="979" alt="screen shot 2018-08-25 at 6 02 41 pm" src="https://user-images.githubusercontent.com/1096738/44738121-8f05e500-aab9-11e8-825e-0079109ff1c1.png">

Got it about the auto-generation — I could see how that would be a pain.

**Comment by bradyvercher** [comment]
Looking good! I'm happy to see you were able to put it to good use.
